[gemini] 
api_key = "AIzaSyBPtUWNBXWX94TKohLxSu_KxPn9WMU81Ww"


[aws]
access_key_id = "YOUR_AWS_ACCESS_KEY"
secret_access_key = "YOUR_AWS_SECRET_KEY"
bucket_name = "skilldrift-data"
region = "ap-south-1"
